// <auto-generated />
namespace TA_Telecom_Task.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addnewTableSMSPhoneNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewTableSMSPhoneNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202102181139394_add-newTable-SMSPhoneNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
