// <auto-generated />
namespace TA_Telecom_Task.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addnewTablePhoneNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewTablePhoneNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202102181055279_add-newTable-PhoneNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
